name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest || echo "No tests found"

    - name: Build Docker image
      run: docker build -t portfolio .

    - name: Push Docker image to DockerHub
      run: |
        echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        docker tag portfolio ${{ secrets.DOCKERHUB_USERNAME }}/portfolio:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/portfolio:latest
